//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_ORM.Test.WORM_Context.Entities
{
    using W_ORM.Layout.Attributes;
    using W_ORM.MSSQL.Attributes;
    
    
    [Table(SchemaName="dbo", TableName="Student", OrdinalPosition=2)]
    public sealed class Student
    {
        
        [FOREIGN_KEY("Department", "DepartmentID")]
        [INT()]
        public int DepartmentID { get; set; } // DepartmentID;
        
        [PRIMARY_KEY()]
        [INT()]
        [NOTNULL()]
        public int StudentID { get; set; } // StudentID;
        
        [NVARCHAR(100)]
        [NOTNULL()]
        public string StudentName { get; set; } // StudentName;
        
        [NVARCHAR(100)]
        [NOTNULL()]
        public string StudentSurName { get; set; } // StudentSurName;
        
        [NVARCHAR(100)]
        [NOTNULL()]
        public string StudentEmail { get; set; } // StudentEmail;
    }
}
