//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_ORM.MYSQL.WORM_Context.Entities
{
    using W_ORM.Layout.Attributes;
    using W_ORM.MYSQL.Attributes;
    
    
    [Table(TableName="Course", OrdinalPosition=3)]
    public sealed class Course
    {
        
        [PRIMARY_KEY()]
        [INT()]
        [NOTNULL()]
        public int CourseID { get; set; } // CourseID;
        
        [VARCHAR(500)]
        [NOTNULL()]
        public string CourseName { get; set; } // CourseName;
        
        [VARCHAR(10)]
        [NOTNULL()]
        public string CourseCredit { get; set; } // CourseCredit;
        
        [FOREIGN_KEY("Department", "DepartmentID")]
        [INT()]
        [NOTNULL()]
        public int DepartmentID { get; set; } // DepartmentID;
    }
}
