//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_ORM.MYSQL.WORM_Context.Entities
{
    using W_ORM.Layout.Attributes;
    using W_ORM.MYSQL.Attributes;
    
    
    [Table(TableName="Department", OrdinalPosition=1)]
    public sealed class Department
    {
        
        [PRIMARY_KEY()]
        [INT()]
        [NOTNULL()]
        public int DepartmentID { get; set; } // DepartmentID;
        
        [VARCHAR(100)]
        [NOTNULL()]
        public string DepartmentName { get; set; } // DepartmentName;
    }
}
